### ISSUE TITLE
Hope add the text description

### ISSUE THREAD

**Issue by Allenlulf** [JoeMinty/Joe-Hadoop#1]
God of Qiao, analysis of the source code hope to add the text description

**Comment by JoeMinty** [comment]
里面有

**Comment by Allenlulf** [comment]
Bring the mechanical keyboard back on Thursday, I want to take it home.

**Comment by JoeMinty** [comment]
s.b gun.

**Comment by Allenlulf** [comment]
？？？

**Comment by JoeMinty** [comment]
useless
